### PR TITLE
Refactor caretEnsemble

### PR DESCRIPTION
**Pull request by zachmayer**
Make caretEnsemble inherit from caretStack.  This make maintenance much easier as it removes all the optimizers, which were getting unwieldy.  Replaced them with a glm, which typically gives the same model weights, with the important caveat that weights can be negative.  This doesn't bother me, but if desired we could use a non-negative regression package.

Also fixed a lot of broken tests and things that broke due to a new caret version.  caretEnsemble should be usable again!

### CODE REVIEW

**Comment by zachmayer** [comment]
So on one build lintr failed: https://travis-ci.org/zachmayer/caretEnsemble/jobs/106112153

And the other build has 3 warnings I'll work on fixing: https://travis-ci.org/zachmayer/caretEnsemble/jobs/106112154

1. I dunno how to fix this one.  I guess it's a ggplot2 issue?
```{R}
checking whether package ‘caretEnsemble’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘grid::arrow’ when loading ‘caretEnsemble’
  Warning: replacing previous import by ‘grid::unit’ when loading ‘caretEnsemble’
```

2. Silly error, I can fix
```{R}
checking S3 generic/method consistency ... WARNING
getMetric:
  function(x, metric, ...)
getMetric.train:
  function(x, metric)
getMetricSD:
  function(x, metric, ...)
getMetricSD.train:
  function(x, metric)
```

2. Silly error, I can fix
```{R}
checking Rd \usage sections ... WARNING
Duplicated \argument entries in documentation object 'getMetric':
  ‘x’ ‘metric’ ‘...’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

**Comment by jknowles** [comment]
I thinks we can fix the first by finding out where @importFrom grid arrow is called and eliminating it. It means somewhere we import grid as a package and somewhere else we import just the function and it is duplicated.

**Comment by zachmayer** [comment]
@jknowles Gotcha.  I'll try it out.

What do you think of the refactor of caretEnsemble to be a sub-class of caretStack?  I like how much it simplifies the code, and all the S3 methods still work.

I actually think we can port all the S3 methods over to caretStack too.

The downside is we lose the optimizers, but those were a headache to maintain anyways.  I think we could make a new package for greedy, forward, non-negative regression/classification, and then add it to the caret package.

That way the optimizers could have their own package, test-suite, issue tracker, etc.

**Comment by zachmayer** [comment]
Ok tests pass locally when `NOT_CRAN="false"` and `NOT_CRAN="true"`, with no warnings, errors, or notes.

I still get this message though, even though I replaced ALL imports with importFrom.  Weird:
```{R}
Note: the specification for S3 class “family” in package ‘MatrixModels’ seems equivalent to one from package ‘lme4’: not turning on duplicate class definitions for this class.
Warning: replacing previous import by ‘grid::arrow’ when loading ‘caretEnsemble’
Warning: replacing previous import by ‘grid::unit’ when loading ‘caretEnsemble’
```

Anyways, at this point I'm going to run `devtools::build_win()` and if that passes ship it to CRAN.

**Comment by zachmayer** [comment]
`devtools::build_win()` passes with 2 NOTES.  I'm writing the warnings off as travis peculiarities.

**Comment by zachmayer** [comment]
Running `build_win()` again with the new imports from base R

**Comment by zachmayer** [comment]
Ok, on this commit, `build_win()` runs without errors, warnings, or notes.  I also get no errors, warnings, or notes in my local tests.

**Comment by zachmayer** [comment]
All right, I'm going to ignore the lint for now.  That's the only failure (and `AS_CRAN="true"` passes):

```{R}
  testthat results ================================================================
  OK: 629 SKIPPED: 2 FAILED: 1
  1. Failure: Code Lint 
```

**Comment by zachmayer** [comment]
:shipit:

**Comment by zachmayer** [comment]
Wahoo!  Passes without issue locally, on travis, and on `build_win()`.  I merged this PR and submitted to CRAN!

**Pull request merged**
