### PR TITLE
Multiclass support for caretList and caretStack #260

### PR DESCRIPTION
**Pull request by zachmayer**
The following changes were made:
 - [x] `predict.caretList` now returns a matrix of probabilities for classification problems.
 - [x] Internally, `makePredObsMatrix` uses probabilities for all but one class.
 - [x] `predict.caretStack` now returns a matrix of probabilities.
 - [x] Functions `setMulticlassExcludedLevel` and `getMulticlassExcludedLevel` can be used to determine which class to exclude. If a class outside the range 1,...,`num_classes` is provided, `makePredObsMatrix` and `predict.caretStack` will use probabilities for ALL classes and a warning will be displayed, as this may cause collinearity issues.
 - [x] All tests have passed, and specific tests for multiclass functionality were added.

`caretEnsemble` still works only for binary classification problems. This is due to the method used, `glm`, which only works with binary class problems. Instead of this method, `caretStack` can be used with other methods, such as `multinom`, as suggested [here](https://stats.stackexchange.com/questions/252222/logistic-regression-for-non-binary-classification-multi-class-in-r).
 
 Rebase of https://github.com/zachmayer/caretEnsemble/pull/260:
- Squashed @antongomez 's 10 commits into 1
- Dropped my 1 multiclass commit, as it is now in main
- Rebased off main
- Resolved conflicts (please check my work!)

### CODE REVIEW

**Comment by zachmayer** [comment]
@antongomez Please review.  I rebased your PR off the modern version of caretEnsemble and resolved the conflicts.  Please check that I resolved the conflicts in your code correctly and confirm that my interpretations were correct.

**Comment by antongomez** [comment]
> @antongomez I rebased the PR off main and resolved conflicts. Please review carefully and confirm my conflict resolution was correct.

I have reviewed your pull request. I found it correct. 

I saw that you included a warning message when `caret.ensemble.multiclass.excluded.level` is out of the range between 1 and the number of classes in the classification problem when the `predict.caretStack` function is called. I think it is a good idea, but it should also be displayed when `train.caretStack` is called and `caret.ensemble.multiclass.excluded.level` is out of the range between 1 and the number of classes in the classification problem. To do this, we can add the same warning inside the `makePredObsMatrix` function, before line 417:

```R
if (getMulticlassExcludedLevel() >= 1 && getMulticlassExcludedLevel() <= num_classes) {
      classes_included <- levels(list_of_models[[1]]$pred$obs)[-getMulticlassExcludedLevel()]
    } else {
      warning("Invalid option ... ")
      classes_included <- levels(list_of_models[[1]]$pred$obs)
}
```

I think the user should be advised not only when calling `predict.caretStack` but also when a caretStack object is trained. What do you think?

**Comment by antongomez** [comment]
Regarding the tests, I frequently get a warning when executing them in several parts of the test code:

```
Warning (test-helper_functions.R:81:3): We can predict
prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
Backtrace:
     ▆
  1. ├─stats::predict(models.class, "Classification", newdata = X.class) at test-helper_functions.R:81:2
  2. └─caretEnsemble:::predict.caretList(...)
  3.   └─base (local) apply_fun(...) at caretEnsemble/R/caretList.R:333:2
  4.     └─base::lapply(X = X, FUN = FUN, ...)
  5.       └─caretEnsemble (local) FUN(X[[i]], ...)
  6.         └─caret::predict.train(x, type = "prob", newdata = newdata, ...) at caretEnsemble/R/caretList.R:338:8
  7.           └─caret::probFunction(...)
  8.             └─method$prob(modelFit = modelFit, newdata = newdata, submodels = param)
  9.               ├─stats::predict(modelFit, newdata, type = "response")
 10.               └─stats::predict.glm(modelFit, newdata, type = "response")
 11.                 └─stats::predict.lm(...)
```

It occurs when we call the predict function with `models.class`. For example, in line 81 of `test-helper_functions.R`, we use it:

```
predict(models.class, "Classification", newdata = X.class)
```
I think it occurs due to collinearity problems in the `X.class` data. I suppose you are not encountering these warnings, so maybe we have different versions of `lm` implementation. To resolve it, we can use `suppressWarnings` or `expect_warning`. What do you think about it? It is a minor problem, but it is not comfortable to check tests when this warning is produced many times.

**Comment by antongomez** [comment]
I didn't see any additional issues, so I think it is done!

**Comment by zachmayer** [comment]
Here's my plan to fix all the warnings: use `glmnet` instead of glm for caretEnsemble.  That should resolve any collinearity issues

**Comment by zachmayer** [comment]
🎉  8 years in the making

**Pull request merged**
